import {BuildingViewer} from './viewer.js';
const $=id=>document.getElementById(id);let viewer,fileData=null,activeJob=null,pollTimer=null,requestEpoch=0;
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n);
function status(text,kind=''){$('status').textContent=text;$('status').className='status '+kind;}
try{viewer=new BuildingViewer($('viewport'));}catch(e){status(e.message,'error');}
const gateNames={all_points:'整体贴合',each_roof_patch:'局部屋面',each_observed_facade:'观测立面',outline:'轮廓',topology:'网格拓扑',all_footprint_components_retained:'轮廓完整性',resolved_partition_adjacency:'屋面邻接'};
function links(obj,report){for(const [id,url] of [['download',obj],['report',report]]){const e=$(id);e.classList.toggle('disabled',!url);e.setAttribute('aria-disabled',String(!url));if(url)e.href=url;else e.removeAttribute('href');}}
function present(data,label,objUrl,reportUrl){
  viewer?.setData(data);viewer?.reset();$('empty').classList.toggle('hidden',!!(data.points?.length||data.model));$('sceneName').textContent=label;
  $('pointCount').textContent=fmt(data.point_count??data.points?.length??0);const m=data.model,v=data.validation;
  $('noiseCount').textContent=m?fmt(m.noise_diagnostics?.excluded_points??0):'—';$('meshCount').textContent=m?`${fmt(m.topology.vertices)} / ${fmt(m.topology.faces)}`:'—';$('p95').textContent=v?v.all_points.p95.toFixed(3):'—';
  $('displayCount').textContent=`显示 ${fmt(data.points?.length||0)} / ${fmt(data.point_count||data.points?.length||0)} 点`;
  if(m){const fail=Object.entries(v?.gates||{}).filter(([,ok])=>!ok).map(([k])=>gateNames[k]||k);$('quality').textContent=v?.accepted?'观测代理门槛通过 · 仍需人工检查':'候选网格已生成 · 需要检查';$('qualityDetail').textContent=v?`未通过：${fail.join('、')||'无'}。开放边 ${m.topology.open_edges}，非流形边 ${m.topology.nonmanifold_edges}。暂无官方 CD / ECD。`:'自动验证未完成，请下载报告查看原因。';}
  else{$('quality').textContent='点云已载入';$('qualityDetail').textContent='点击“生成建筑网格”开始处理，过程中可旋转检查原始点云。';}
  links(objUrl,reportUrl);
}
async function json(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error||`请求失败 ${r.status}`);return data;}
async function inputFile(file){if(!file)return;if(activeJob){status('当前任务仍在计算，完成后可以上传下一栋。','error');return;}try{
  if(file.size>24*1024*1024)throw new Error('文件超过 24 MB。');const text=(await file.text()).replace(/^\uFEFF/,'');const lines=text.split(/\r?\n/),points=[];
  for(let i=0;i<lines.length;i++){const line=lines[i].split('#')[0].trim();if(!line)continue;const p=line.split(/\s+/).map(Number);if(p.length!==3||p.some(n=>!Number.isFinite(n)))throw new Error(`第 ${i+1} 行格式错误，需要三个有限数值 X Y Z。`);points.push(p);if(points.length>300000)throw new Error('最多支持 300000 点，请拆分为单栋点云。');}
  if(points.length<20)throw new Error('至少需要 20 个 XYZ 点。');fileData={text,name:file.name};requestEpoch++;$('fileLabel').textContent=file.name;$('fileInfo').textContent=`${fmt(points.length)} 个点 · ${(file.size/1024).toFixed(1)} KB · 本地文件`;$('generate').disabled=false;
  const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const p of points)for(let i=0;i<3;i++){lo[i]=Math.min(lo[i],p[i]);hi[i]=Math.max(hi[i],p[i]);}const skip=Math.max(1,Math.ceil(points.length/22000));present({points:points.filter((_,i)=>i%skip===0),point_count:points.length,bounds:[lo,hi]},file.name);status('点云已载入。可调整噪声处理和底高，然后生成网格。');
 }catch(e){fileData=null;$('generate').disabled=true;status(e.message,'error');}}
$('file').addEventListener('change',e=>inputFile(e.target.files[0]));for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('drag');});for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('drag');});$('dropzone').addEventListener('drop',e=>inputFile(e.dataTransfer.files[0]));
$('generate').addEventListener('click',async()=>{if(!fileData||activeJob)return;const epoch=++requestEpoch;try{const value=$('ground').value;const ground=value===''?null:Number(value);if(ground!==null&&!Number.isFinite(ground))throw new Error('底高必须为有限数字。');$('generate').disabled=true;links(null,null);status('正在提交点云…','busy');const job=await json('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fileData,ground_z:ground,noise:$('noise').value})});activeJob=job.id;$('loadExample').disabled=true;$('file').disabled=true;
 const poll=async()=>{try{const s=await json(`/api/jobs/${job.id}`);if(s.status==='complete'){clearTimeout(pollTimer);const data=await json(`/api/jobs/${job.id}/preview`);if(epoch===requestEpoch)present(data,job.name,`/api/jobs/${job.id}/obj`,`/api/jobs/${job.id}/report`);status(`生成完成 · ${s.seconds.toFixed(1)} 秒。下载 OBJ 前请检查屋面与立面接缝。`);finish();}else if(s.status==='failed'){throw new Error(s.error||'重建失败。');}else{status(s.status==='queued'?'任务已排队，等待本地计算…':'正在拟合屋面、补全立面并验证全部原始点…','busy');pollTimer=setTimeout(poll,1000);}}catch(e){status(e.message,'error');finish();}};poll();
 }catch(e){status(e.message,'error');finish();}});
function finish(){activeJob=null;$('generate').disabled=!fileData;$('loadExample').disabled=false;$('file').disabled=false;}
async function refresh(){try{const data=await json('/api/examples');const value=$('example').value;$('example').replaceChildren();if(!data.length){$('example').add(new Option('样例生成中，请稍后刷新',''));return;}const groups=new Map();for(const e of data){if(!groups.has(e.group)){const g=document.createElement('optgroup');g.label=e.group;groups.set(e.group,g);$('example').append(g);}const option=new Option(e.label,e.key);groups.get(e.group).append(option);}if(data.some(e=>e.key===value))$('example').value=value;}catch(e){status(e.message,'error');}}
$('refresh').onclick=refresh;$('loadExample').onclick=async()=>{const key=$('example').value;if(!key||activeJob)return;const epoch=++requestEpoch;try{$('loadExample').disabled=true;status('正在载入样例…','busy');const data=await json('/api/examples/'+key);if(epoch!==requestEpoch)return;present(data,data.label,data.model?data.obj_url:null,data.validation?data.report_url:null);status(data.input_available===false?'网格与报告已载入；本机没有该样例原始点云，无法显示叠加。':'样例已载入。切换点云 / 网格 / 叠加检查轮廓和局部结构。');}catch(e){status(e.message,'error');}finally{$('loadExample').disabled=false;}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));if(viewer){viewer.mode=b.dataset.mode;viewer.render();}});for(const id of ['top','front','perspective','reset'])$(id).onclick=()=>viewer?.reset(id);
$('showNoise').onchange=()=>{if(viewer){viewer.noise=$('showNoise').checked;viewer.render();}};$('showEdges').onchange=()=>{if(viewer){viewer.edges=$('showEdges').checked;viewer.render();}};
json('/api/health').then(d=>$('version').textContent='算法 v'+d.algorithm_version).catch(e=>status('本地服务不可用：'+e.message,'error'));refresh();
